name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          persist-credentials: false 

      - name: Build 
        run: |
          npm install
          npm run-script build
       
        env:
          CLIENT_ID: ${{secrets.CLIENT_ID}}
          CLIENT_ID_FB: ${{secrets.CLIENT_ID_FB}}
          CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
          CLIENT_SECRET_FB: ${{secrets.CLIENT_SECRET_FB}}
          MONGODB_ATLAS: ${{secrets.MONGODB_ATLAS}}
          SESSION_SECRETS: ${{secrets.SESSION_SECRETS}}
          
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
